// src/app/metadata.ts
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "AbbyCE",
  description: "Generated by create next app",
  icons: {
    icon: "/app/favicon.ico",
  },
};
